### ISSUE TITLE
can't use sh start.sh to open 4200 port

### ISSUE THREAD

**Issue by cheng-orange** [exadel-inc/CompreFace#679]
**Describe the bug**

I can't use sh start.sh to open 4200 port,but 8000 is available

ERROR: Service 'compreface-core' failed to build: The command '/bin/bash -c python -m src.services.facescan.plugins.setup' returned a non-zero code: 1

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [edge]
 - Version [latest]

**Additional context**
2021-12-15 12:45:01.920327: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fcee8187ed0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1im5Qq006ZEV_tViKh3cgia_Q4jJ13bRK (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcee8187ed0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/ml/src/services/facescan/plugins/setup.py", line 22, in <module>
    plugin.ml_model.download_if_not_exists()
  File "/app/ml/src/services/facescan/plugins/base.py", line 60, in download_if_not_exists
    self._download(self.url, tmpfile)
  File "/app/ml/src/services/facescan/plugins/base.py", line 69, in _download
    return gdown.download(url, output)
  File "/usr/local/lib/python3.7/site-packages/gdown/download.py", line 147, in download
    res = sess.get(url, headers=headers, stream=True, verify=verify)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1im5Qq006ZEV_tViKh3cgia_Q4jJ13bRK (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcee8187ed0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by pospielov** [comment]
First of all, instructions for 4200 ports are only for UI developers. If you don't want to develop UI for CompreFace, you don't need it.
Second, looks like your build fails because you don't have access to google drive. We do not store models in GitHub, we store them in Google Drive. And during the build, we download them and put in docker image, so you don't need access to it in runtime
